### ISSUE TITLE
Tooltip works, but an error appears in the error log on mouse-over activation (Safari) DokuWiki 2023-04-04 "Jack Jackrum"

### ISSUE THREAD

**Issue by grockle1** [giterlizzi/dokuwiki-plugin-bootswrapper#143]
2023-04-20 12:43:07
E_WARNING: Undefined array key "html"
/is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/lib/plugins/bootswrapper/syntax/tooltip.php(55)
#0 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/lib/plugins/bootswrapper/syntax/tooltip.php(55): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/is/htdocs/wp12...', 55)
#1 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_tooltip->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#2 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_to...', Array, 1, '<tooltip title=...')
#3 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
#4 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/parserutils.php(96): p_cached_output('/is/htdocs/wp12...', 'xhtml', 'start')
#5 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml('start', 0, true, '')
#6 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#7 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core('show')
#9 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
#10 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#11 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#12 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#13 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/inc/actions.php(27): include('/is/htdocs/wp12...')
#14 /is/htdocs/wp12031014_BU146GL3CY/www/www/dokuwiki/doku.php(126): act_dispatch()
#15 {main}

**Comment by yaynstuff** [comment]
Now seeing the same thing after upgrading our installation to the latest version..

**Comment by Miro-Collas** [comment]
Same here - FWIW

**Comment by Miro-Collas** [comment]
Yes... that error, and others:

` 2023-08-13 21:26:56E_WARNING: Undefined array key "size"/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/well.php(42)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/well.php(42): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 42)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_well->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_we...', Array, 1, '<well>')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_inventory')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('fs_inventory', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main}

2023-08-13 21:27:11E_WARNING: Undefined array key 4/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/text.php(63)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/text.php(63): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 63)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_text->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_te...', Array, 4, '</text>')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'start')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('start', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main}

2023-08-13 21:30:47E_WARNING: Undefined variable $dismiss/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/alert.php(60)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/alert.php(60): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined varia...', '/home/fswiki/pu...', 60)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_alert->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_al...', Array, 1, '<alert type="in...')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_missing_inve...')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('fs_missing_inve...', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main}

2023-08-13 21:40:08E_WARNING: Undefined array key "html"/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/tooltip.php(55)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/tooltip.php(55): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 55)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_tooltip->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_to...', Array, 1, '<tooltip title=...')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_chat')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('fs_chat', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main} `

**Comment by Miro-Collas** [comment]
More....

`2023-08-13 23:35:31E_WARNING: Undefined array key 4/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(45)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(45): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 45)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_accordion->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_ac...', Array, 4, '</accordion>')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_older_downlo...')
    #5 /home/fswiki/public_html/feed.php(395): p_wiki_xhtml('fs_older_downlo...', '', false)
    #6 /home/fswiki/public_html/feed.php(96): rss_buildItems(Object(UniversalFeedCreator), Array, Array)
    #7 {main}

2023-08-13 23:35:32E_WARNING: Trying to access array offset on value of type bool/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(51)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(51): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 51)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_accordion->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_ac...', Array, 1, '<accordion>')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'new_residents:e...')
    #5 /home/fswiki/public_html/feed.php(395): p_wiki_xhtml('new_residents:e...', '', false)
    #6 /home/fswiki/public_html/feed.php(96): rss_buildItems(Object(UniversalFeedCreator), Array, Array)
    #7 {main}

2023-08-13 23:35:32E_WARNING: Undefined array key 4/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(45)
    #0 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/accordion.php(45): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 45)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_bootswrapper_accordion->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('bootswrapper_ac...', Array, 4, '</accordion>')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'new_residents:e...')
    #5 /home/fswiki/public_html/feed.php(395): p_wiki_xhtml('new_residents:e...', '', false)
    #6 /home/fswiki/public_html/feed.php(96): rss_buildItems(Object(UniversalFeedCreator), Array, Array)
    #7 {main}`

**Comment by Miro-Collas** [comment]
@giterlizzi  This can be closed, I believe. I tested with "Mort" on PHP 8.3, and no warnings or errors. :-)
