### ISSUE TITLE
bootstrap.php warning in simplexml_load_string()

### ISSUE THREAD

**Issue by Miro-Collas** [giterlizzi/dokuwiki-plugin-bootswrapper#144]
Release 2023-04-04a "Jack Jackrum"
Template v2022-07-27 (stable/20220727)
PHP 8.1

```
2023-08-19 05:17:28E_WARNING: simplexml_load_string(): &lt;callout stop/&gt;/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php(227)
    #0 [internal function]: dokuwiki\ErrorHandler::errorHandler(2, 'simplexml_load_...', '/home/fswiki/pu...', 227)
    #1 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php(227): simplexml_load_string('<callout stop/>')
    #2 /home/fswiki/public_html/inc/parser/handler.php(284): syntax_plugin_bootswrapper_bootstrap->handle('<callout stop>', 1, 1205, Object(Doku_Handler))
    #3 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<callout stop>', 1, 1205, 'bootswrapper_ca...')
    #4 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(204): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('<callout stop>', 1, 1205)
    #5 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '<callout stop>', 'plugin_bootswra...', 1205, 1205)
    #6 /home/fswiki/public_html/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('NOTE: Remember ...')
    #7 /home/fswiki/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n===== Inventor...')
    #8 /home/fswiki/public_html/inc/parserutils.php(198): p_get_instructions('===== Inventory...')
    #9 /home/fswiki/public_html/inc/parserutils.php(158): p_cached_instructions('/home/fswiki/pu...', false, 'inventory_filte...')
    #10 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'inventory_filte...')
    #11 /home/fswiki/public_html/feed.php(395): p_wiki_xhtml('inventory_filte...', '', false)
    #12 /home/fswiki/public_html/feed.php(96): rss_buildItems(Object(UniversalFeedCreator), Array, Array)
    #13 {main}
2023-08-19 05:17:28E_WARNING: simplexml_load_string(): ^/home/fswiki/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php(227)
    #0 [internal function]: dokuwiki\ErrorHandler::errorHandler(2, 'simplexml_load_...', '/home/fswiki/pu...', 227)
    #1 /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/bootstrap.php(227): simplexml_load_string('<callout stop/>')
    #2 /home/fswiki/public_html/inc/parser/handler.php(284): syntax_plugin_bootswrapper_bootstrap->handle('<callout stop>', 1, 1205, Object(Doku_Handler))
    #3 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<callout stop>', 1, 1205, 'bootswrapper_ca...')
    #4 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(204): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('<callout stop>', 1, 1205)
    #5 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '<callout stop>', 'plugin_bootswra...', 1205, 1205)
    #6 /home/fswiki/public_html/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('NOTE: Remember ...')
    #7 /home/fswiki/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n===== Inventor...')
    #8 /home/fswiki/public_html/inc/parserutils.php(198): p_get_instructions('===== Inventory...')
    #9 /home/fswiki/public_html/inc/parserutils.php(158): p_cached_instructions('/home/fswiki/pu...', false, 'inventory_filte...')
    #10 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'inventory_filte...')
    #11 /home/fswiki/public_html/feed.php(395): p_wiki_xhtml('inventory_filte...', '', false)
    #12 /home/fswiki/public_html/feed.php(96): rss_buildItems(Object(UniversalFeedCreator), Array, Array)
    #13 {main}
```

**Comment by Miro-Collas** [comment]
@giterlizzi  This can be closed. I tested with "Mort" on PHP 8.3, and no warnings or errors. :-)
